"use client";

import Link from "next/link";
import { ArrowLeft, Droplets, HeartPulse, ShieldCheck, Syringe, UserRound } from "lucide-react";
import { useDashboard } from "@/hooks/use-dashboard";

function formatEnum(value: unknown) { if (!value) return "Not recorded"; return String(value).toLowerCase().replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function activeRecord(record: any) { return record?.status !== "INACTIVE" && record?.status !== "RESOLVED" && !record?.resolvedAt; }
function InfoCard({ label, value, description }: { label: string; value: string; description?: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-medium text-slate-400">{label}</p><p className="mt-2 text-xl font-bold text-[#0b2d54]">{value}</p>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div>; }

export default function HealthPassportPage() {
  const { data, loading, error, reload } = useDashboard();
  const profile = data?.profile ?? null;
  const patient = data?.patient ?? null;
  const snapshot = data?.healthSnapshot;
  const healthPassport = data?.healthPassport ?? {};
  const allergies = Array.isArray(data?.allergies) && data.allergies.length > 0 ? data.allergies : (snapshot?.allergies ?? []);
  const conditions = Array.isArray(data?.conditions) && data.conditions.length > 0 ? data.conditions : (snapshot?.activeConditions ?? []);
  const immunizations = Array.isArray(data?.immunizations) && data.immunizations.length > 0 ? data.immunizations : (snapshot?.immunizations ?? []);
  const emergencyContacts = data?.emergencyContacts ?? [];
  const activeAllergies = allergies.filter(activeRecord);
  const activeConditions = conditions.filter(activeRecord);
  const firstName = profile?.preferredName || profile?.firstName || patient?.firstName || "Patient";
  const fullName = [firstName, profile?.lastName || patient?.lastName].filter(Boolean).join(" ") || "Patient";
  const bloodType = healthPassport?.bloodType ?? snapshot?.bloodType;
  const rhesusFactor = healthPassport?.rhesusFactor ?? snapshot?.rhesusFactor;

  return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
    <Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-medium text-[#0b2d54] hover:text-[#24c1c4]"><ArrowLeft className="h-4 w-4" />Back to Health Home</Link>
    <div className="mb-8"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[#24c1c4]/10 px-3 py-1 text-xs font-semibold text-[#0b2d54]"><ShieldCheck className="h-3.5 w-3.5" />My health</div><h1 className="text-3xl font-bold tracking-tight text-[#0b2d54] sm:text-4xl">Health passport</h1><p className="mt-2 max-w-2xl text-slate-500">Your essential health information in one place, ready to reference when you need it.</p></div>
    {loading && <div className="mb-6 rounded-2xl border border-slate-200 bg-white p-4 text-sm text-slate-500">Loading your health passport...</div>}
    {error && !loading && <div className="mb-6 rounded-2xl border border-red-200 bg-white p-6"><h2 className="font-semibold text-[#0b2d54]">We couldn't load your health passport</h2><button onClick={reload} className="mt-4 rounded-xl bg-[#0b2d54] px-4 py-2 text-sm font-semibold text-white">Try again</button></div>}
    <section className="mb-6 rounded-2xl bg-[#0b2d54] p-6 text-white sm:p-8"><div className="flex items-center gap-5"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/10"><UserRound className="h-8 w-8" /></div><div><p className="text-sm text-slate-300">Health passport for</p><h2 className="mt-1 text-2xl font-bold">{fullName}</h2>{profile?.dateOfBirth && <p className="mt-2 text-sm text-slate-300">Date of birth: {profile.dateOfBirth}</p>}</div></div></section>
    <section className="mb-6"><h2 className="mb-4 text-lg font-semibold text-[#0b2d54]">Blood information</h2><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6"><Droplets className="h-5 w-5 text-[#24c1c4]" /><p className="mt-4 text-xs font-medium text-slate-400">Blood type</p><p className="mt-1 text-3xl font-bold text-[#0b2d54]">{formatEnum(bloodType)}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><HeartPulse className="h-5 w-5 text-[#24c1c4]" /><p className="mt-4 text-xs font-medium text-slate-400">Rhesus factor</p><p className="mt-1 text-3xl font-bold text-[#0b2d54]">{formatEnum(rhesusFactor)}</p></div></div></section>
    <section className="mb-6"><h2 className="mb-4 text-lg font-semibold text-[#0b2d54]">Important information</h2><div className="grid gap-4 md:grid-cols-2"><InfoCard label="Organ donor" value={healthPassport?.organDonor === true ? "Yes" : healthPassport?.organDonor === false ? "No" : "Not recorded"} description="Organ donation preference" /><InfoCard label="Allergies" value={String(activeAllergies.length)} description={activeAllergies.length ? "Active allergies recorded" : "No active allergies recorded"} /><InfoCard label="Health conditions" value={String(activeConditions.length)} description={activeConditions.length ? "Active conditions recorded" : "No active conditions recorded"} /><InfoCard label="Immunizations" value={String(immunizations.length)} description={immunizations.length ? "Immunizations recorded" : "No immunizations recorded"} /><InfoCard label="Emergency contacts" value={String(emergencyContacts.length)} description="Contacts available in an emergency" /></div></section>
    <section className="mb-6"><h2 className="mb-4 text-lg font-semibold text-[#0b2d54]">Allergies</h2><div className="rounded-2xl border border-slate-200 bg-white p-6">{activeAllergies.length ? <div className="flex flex-wrap gap-2">{activeAllergies.map((allergy: any) => <span key={allergy?.id ?? allergy?.name} className="rounded-full bg-rose-50 px-3 py-1.5 text-sm font-medium text-rose-600">{allergy?.allergy?.name || allergy?.name || "Allergy"}</span>)}</div> : <p className="text-sm text-slate-500">No allergies are currently recorded.</p>}</div></section>
    <section className="mb-6"><h2 className="mb-4 text-lg font-semibold text-[#0b2d54]">Active conditions</h2><div className="rounded-2xl border border-slate-200 bg-white p-6">{activeConditions.length ? <div className="grid gap-3 sm:grid-cols-2">{activeConditions.map((condition: any) => <div key={condition?.id ?? condition?.name} className="rounded-xl bg-slate-50 p-4"><p className="font-medium text-[#0b2d54]">{condition?.condition?.name || condition?.name || "Health condition"}</p></div>)}</div> : <p className="text-sm text-slate-500">No active health conditions are currently recorded.</p>}</div></section>
    <section className="mb-6"><div className="mb-4 flex items-center gap-2"><Syringe className="h-5 w-5 text-[#24c1c4]" /><h2 className="text-lg font-semibold text-[#0b2d54]">Immunizations</h2></div><div className="rounded-2xl border border-slate-200 bg-white p-6">{immunizations.length ? <div className="grid gap-3 sm:grid-cols-2">{immunizations.map((immunization: any) => <div key={immunization?.id ?? immunization?.immunizationId} className="rounded-xl bg-slate-50 p-4"><p className="font-medium text-[#0b2d54]">{immunization?.immunization?.name || immunization?.name || immunization?.vaccineName || "Immunization"}</p>{immunization?.administeredAt && <p className="mt-1 text-sm text-slate-500">Administered: {new Date(immunization.administeredAt).toLocaleDateString()}</p>}{immunization?.doseNumber != null && <p className="mt-1 text-sm text-slate-500">Dose {immunization.doseNumber}</p>}</div>)}</div> : <div className="flex items-center gap-3"><Syringe className="h-5 w-5 text-slate-400" /><p className="text-sm text-slate-500">No immunizations are currently recorded.</p></div>}</div></section>
    <div className="mt-8 rounded-2xl border border-[#24c1c4]/20 bg-[#24c1c4]/5 p-5"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-[#0b2d54]" /><div><h3 className="font-semibold text-[#0b2d54]">Your health passport is private</h3><p className="mt-1 text-sm leading-6 text-slate-500">Keep this information accurate and up to date. Always confirm important medical information with your healthcare professional when necessary.</p></div></div></div>
  </div></main>;
}
