import { api } from "@/lib/api";

export type HealthGoalProgressUpdate = { id: string; title: string; category?: string; targetValue?: number | string | null; currentValue?: number | string | null; unit?: string | null; progress?: Array<{ currentValue?: number | string | null; progressPercent?: number | string | null; status?: string | null; measuredAt?: string; }>; };
export type HealthGoalMetricEventsResponse = { count: number; events: Array<{ id: string; loggedValue: number; occurredAt: string; source: string; sourceId?: string | null; }>; };
export type HealthGoalInput = { patientId: string; practitionerId?: string; carePlanId?: string; patientMedicationId?: string; title: string; description?: string; category: string; priority?: string; status?: string; targetValue?: string; currentValue?: string; unit?: string; targetDate?: string; metricType?: string; metricKey?: string; frequency?: "DAILY" | "WEEKLY" | "TOTAL"; frequencyTarget?: string; aggregation?: "SUM" | "LATEST" | "AVERAGE" | "MIN" | "MAX"; comparison?: "AT_LEAST" | "AT_MOST" | "CLOSEST" | "INCREASE_TO" | "DECREASE_TO"; guidanceText?: string; };
export type HealthGoalListResponse = { data: any[]; pagination?: { page: number; limit: number; total: number; totalPages: number } };
export type WeightGoalIntelligence = {
  goal: { id: string; title: string; comparison: string; targetValue: number | null; unit?: string | null; targetDate?: string | null; priority?: string; status?: string; createdAt?: string };
  profile: { age: number | null; gender?: string | null; heightCm: number | null; currentWeightKg: number | null; currentBmi: number | null; baselineWeightKg: number | null; baselineBmi: number | null; adultBmiApplicable: boolean };
  weightPlan: { direction: "LOSE" | "GAIN" | "MAINTAIN"; targetWeightKg: number | null; requestedChangeKg: number | null; remainingChangeKg: number | null; daysRemaining: number | null; requiredDailyChangeKg: number | null; requiredWeeklyChangeKg: number | null; status: "PLANNING" | "ON_TARGET" | "TARGET_REACHED" | "DATE_REACHED" | "NO_TARGET_DATE" };
  healthContext: { connectedGoals: Array<{ title: string; category: string; relationshipType: string; direction: string }>; activeConditions: Array<{ name: string; chronic: boolean; severity: string | null; stage: string | null }>; activeMedications: Array<{ name: string; dosage: string | null; frequency: string | null; indication: string | null; sideEffectsRecorded: boolean }> };
  weight: { latestKg: number | null; average7dKg: number | null; average30dKg: number | null; changeKg: number | null; percentChange: number | null; trendKgPerWeek: number | null; dataPoints: number; maintenanceBand?: { min: number; max: number } | null; withinMaintenanceBand: boolean | null; targetWeightKg: number | null; requestedChangeKg?: number | null; targetBmi: number | null; targetBmiStatus: "BELOW_RANGE" | "WITHIN_RANGE" | "OVERWEIGHT" | "OBESITY_CLASS_1" | "OBESITY_CLASS_2" | "OBESITY_CLASS_3" | "ABOVE_RANGE" | "OBESITY_RANGE" | null; targetNeedsReview: boolean; lowerScreeningWeightKg: number | null; upperScreeningWeightKg: number | null; status: "STABLE" | "DRIFTING_UP" | "DRIFTING_DOWN" | "NEEDS_REVIEW" | "INSUFFICIENT_DATA" };
  checkIn: { dataPoints: number; averageSleepHours: number | null; averageStress: number | null; averageExerciseMinutes: number | null; averageWaterIntakeMl: number | null };
  clinicalContext: { activeMedicationCount: number; activeConditionCount: number; recentSymptomCount: number; symptomsDataAvailable: boolean };
  relationships: Array<{ id: string; direction: string; relationshipType: string; rationale?: string | null; goal: { id: string; title: string; category: string; status: string; targetValue?: number | null; unit?: string | null; targetDate?: string | null } }>;
  recommendedSupportingGoals: Array<{ category: string; rationale: string }>;
  todayFocus?: {
    actions: Array<{ id: string; label: string; description: string; href: string; priority: "PRIMARY" | "SUPPORTING" }>;
    dataFreshness: { weightDataNeedsRefresh: boolean; checkInNeedsCompletion: boolean; latestWeightAt?: string | null };
  };
};

const deletedGoalIds = new Set<string>();
const medicationIdFromCurrentUrl = () => { if (typeof window === "undefined") return undefined; const params = new URLSearchParams(window.location.search); if (params.get("open") !== "medication") return undefined; return params.get("patientMedicationId")?.trim() || params.get("associatedMedicationId")?.trim() || params.get("medicationId")?.trim() || undefined; };
const notifyGoalChange = (goalId?: string) => { if (typeof window !== "undefined") window.dispatchEvent(new CustomEvent("sympto:health-goal-updated", { detail: goalId ? { goalId } : undefined })); };
const normalizeGoalInput = (input: HealthGoalInput | Partial<HealthGoalInput>) => { const category = String(input.category ?? "").toUpperCase(); const medicationIdentity = input.patientMedicationId || medicationIdFromCurrentUrl(); const withMedicationIdentity = category === "MEDICATION" && medicationIdentity ? { ...input, patientMedicationId: medicationIdentity } : input; if (category === "SMOKING") return { ...withMedicationIdentity, metricType: "SMOKING", metricKey: "smoking.cigarettes", frequency: "DAILY" as const, aggregation: "LATEST" as const, comparison: "AT_MOST" as const, unit: input.unit || "cigarettes/day" }; if (category === "ALCOHOL") return { ...withMedicationIdentity, metricType: "ALCOHOL", metricKey: "alcohol.drinks", frequency: "WEEKLY" as const, aggregation: "SUM" as const, comparison: "AT_MOST" as const, unit: input.unit || "drinks/week" }; if (category === "EXERCISE") return { ...withMedicationIdentity, metricType: "EXERCISE", metricKey: "exercise.minutes", frequency: "WEEKLY" as const, aggregation: "SUM" as const, comparison: "AT_LEAST" as const, unit: input.unit || "mins/week" }; return withMedicationIdentity; };
const sameMedicationGoal = (goal: any, patientMedicationId: string) => { if (!goal || String(goal.category ?? "").toUpperCase() !== "MEDICATION") return false; if (String(goal.status ?? "").toUpperCase() === "ARCHIVED") return false; return String(goal.patientMedicationId ?? "") === patientMedicationId; };
const filterDeletedGoals = (payload: any): any => { if (Array.isArray(payload)) return payload.filter((goal) => !deletedGoalIds.has(String(goal?.id))); if (payload && Array.isArray(payload.data)) return { ...payload, data: payload.data.filter((goal: any) => !deletedGoalIds.has(String(goal?.id))) }; return payload; };

class HealthGoalsService {
  async list(patientId: string): Promise<HealthGoalListResponse> { const response = await api.get("/health-goals", { params: { patientId, page: 1, limit: 100 } }); return filterDeletedGoals(response.data?.data ?? response.data); }
  async create(input: HealthGoalInput) { const normalized = normalizeGoalInput(input); const category = String(normalized.category ?? "").toUpperCase(); const patientMedicationId = category === "MEDICATION" ? String(normalized.patientMedicationId ?? "").trim() : ""; if (patientMedicationId) { const existingGoals = await this.list(input.patientId); const existing = existingGoals.data.find((goal: any) => sameMedicationGoal(goal, patientMedicationId)); if (existing) return existing; } const response = await api.post("/patient-health-goals", normalized); const goal = response.data?.data ?? response.data; if (goal?.id) deletedGoalIds.delete(String(goal.id)); notifyGoalChange(); return goal; }
  async update(id: string, input: Partial<HealthGoalInput>) { const response = await api.patch(`/patient-health-goals/${id}`, normalizeGoalInput(input)); const goal = response.data?.data ?? response.data; deletedGoalIds.delete(String(id)); notifyGoalChange(); return goal; }
  async configureMetric(id: string, config: Pick<HealthGoalInput, "metricType" | "metricKey" | "frequency" | "frequencyTarget" | "aggregation" | "comparison" | "guidanceText">) { const metricType = String((config as any).metricType ?? "").toUpperCase(); const normalized = metricType === "SMOKING" ? { ...config, metricType: "SMOKING", metricKey: "smoking.cigarettes", frequency: "DAILY" as const, aggregation: "LATEST" as const, comparison: "AT_MOST" as const } : metricType === "ALCOHOL" ? { ...config, metricType: "ALCOHOL", metricKey: "alcohol.drinks", frequency: "WEEKLY" as const, aggregation: "SUM" as const, comparison: "AT_MOST" as const } : metricType === "EXERCISE" ? { ...config, metricType: "EXERCISE", metricKey: "exercise.minutes", frequency: "WEEKLY" as const, aggregation: "SUM" as const, comparison: "AT_LEAST" as const } : config; const response = await api.patch(`/patient-health-goals/${id}/metric-config`, normalized); const result = response.data?.data ?? response.data; deletedGoalIds.delete(String(id)); notifyGoalChange(); return result; }
  async syncMetricEvent(input: { metricType: string; metricKey: string; loggedValue: number; occurredAt?: string; source?: string; sourceId?: string }) { const response = await api.post("/health-goals/metric-event", input); return response.data?.data ?? response.data; }
  async logSmoking(id: string, cigarettes: number, dayKey: string) { const response = await api.post(`/patient-health-goals/${id}/smoking-log`, { cigarettes, dayKey }); return response.data?.data ?? response.data; }
  async logAlcohol(id: string, currentWeekTotal: number, drinks: number) { const nextTotal = Math.max(0, Number(currentWeekTotal) + Number(drinks)); const response = await api.patch(`/patient-health-goals/${id}`, { currentValue: String(nextTotal) }); return response.data?.data ?? response.data; }
  async remove(id: string) { const response = await api.delete(`/patient-health-goals/${id}`); deletedGoalIds.add(String(id)); const result = response.data?.data ?? response.data; notifyGoalChange(String(id)); return result; }
  async recordProgress(goalId: string, currentValue: number, notes?: string): Promise<HealthGoalProgressUpdate> { const { data } = await api.post(`/health-goals/${goalId}/progress`, { currentValue: String(currentValue), ...(notes ? { notes } : {}) }); return data.data ?? data; }
  async getWeightGoalIntelligence(id: string): Promise<WeightGoalIntelligence> { const response = await api.get(`/patient-health-goals/${id}/intelligence`); return response.data?.data ?? response.data; }
  async getMetricEvents(metricType: string, metricKey: string, from: Date, to: Date, source?: string): Promise<HealthGoalMetricEventsResponse> { const response = await api.get(`/health-goals/metric-events`, { params: { metricType, metricKey, from: from.toISOString(), to: to.toISOString(), ...(source ? { source } : {}) } }); return response.data?.data ?? response.data; }
}

export const healthGoalsService = new HealthGoalsService();