"use client";

import Link from "next/link";
import { useMemo, useState, type ReactNode } from "react";
import { ArrowLeft, Check, ChevronDown, Clock3, FileText, Pill, Plus, ShieldCheck, Sparkles } from "lucide-react";
import { useDashboard } from "@/hooks/use-dashboard";
import { MedicationReminderButton } from "@/components/medications/MedicationReminderButton";
import { MedicationAdherenceActions } from "@/components/medications/MedicationAdherenceActions";
import { onboardingService } from "@/services/onboarding.service";
import { api } from "@/lib/api";
import type { MedicationItem, UpdatePatientMedicationsDto } from "@/types/onboarding";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const FREQUENCIES = [
  ["ONCE_DAILY", "Once a day"], ["TWICE_DAILY", "Twice a day"], ["THREE_TIMES_DAILY", "Three times a day"],
  ["FOUR_TIMES_DAILY", "Four times a day"], ["AS_NEEDED", "As needed"], ["WEEKLY", "Once a week"], ["OTHER", "Other"]
] as const;
const ROUTES = [
  ["ORAL", "By mouth"], ["INHALATION", "Inhaled"], ["INJECTION", "Injection"], ["TOPICAL", "Applied to skin"],
  ["OPHTHALMIC", "Eye drops"], ["OTIC", "Ear drops"], ["OTHER", "Other"]
] as const;
const DOSES = ["5 mg", "10 mg", "20 mg", "25 mg", "40 mg", "50 mg", "75 mg", "100 mg", "150 mg", "200 mg", "250 mg", "300 mg", "400 mg", "500 mg", "600 mg", "800 mg", "1 g", "5 mL", "10 mL", "1 tablet", "2 tablets", "1 capsule", "2 capsules", "Other"];
const PRESCRIBERS = ["Doctor", "Specialist", "Clinic / nurse", "Pharmacist", "Self / over the counter", "Other"];
const REASONS = ["Pain relief", "Blood pressure", "Diabetes", "Cholesterol", "Heart health", "Infection", "Inflammation", "Allergy", "Asthma / breathing", "Mental health", "Hormone treatment", "Contraception", "Vitamin / supplement", "Other"];
const INSTRUCTIONS = ["Take with water", "Take with food", "Take after food", "Take before food", "Take on an empty stomach", "Take at bedtime", "Take in the morning", "Use as directed", "Other"];
const SIDE_EFFECTS = ["None noticed", "Nausea", "Dizziness", "Headache", "Stomach upset", "Sleepiness", "Diarrhoea", "Constipation", "Rash", "Other"];
const EFFECTIVENESS = [["Helping", "Helping"], ["Helping a little", "Helping a little"], ["Not helping", "Not helping"], ["Unsure", "Unsure"], ["Too early to tell", "Too early to tell"]] as const;

function medicationId(m: any) { return m?.patientMedicationId || m?.patientMedication?.id || m?.id || null; }
function formatEnum(value: unknown) { if (!value) return "Not specified"; return String(value).toLowerCase().replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase()); }
function formatCategoryLabel(value: unknown) { const raw = String(value || "").trim().toUpperCase(); const map: Record<string, string> = { ANTIDIABETIC: "Diabetes medicine", NSAID: "Anti-inflammatory pain medicine", ANALGESIC: "Pain relief medicine", CALCIUM_CHANNEL_BLOCKER: "Blood pressure medicine", THYROID: "Thyroid medicine", DERMATOLOGY: "Skin medicine", ANTIBIOTIC: "Antibiotic", ANTIDEPRESSANT: "Antidepressant", ANTIHISTAMINE: "Allergy medicine", BRONCHODILATOR: "Breathing medicine" }; return map[raw] || formatEnum(raw); }
function formatDosageForm(value: unknown) { const raw = String(value || "").trim(); if (!raw) return "Not specified"; return raw.replace(/\btablet\b/gi, "tablet").replace(/\bcapsule\b/gi, "capsule").replace(/\bsolution\b/gi, "liquid").replace(/\bsuspension\b/gi, "liquid").replace(/\bcream\b/gi, "cream").replace(/\bointment\b/gi, "ointment"); }
function formatRouteLabel(value: unknown) { const route = String(value || "").trim().toUpperCase(); const map: Record<string, string> = { ORAL: "By mouth", INHALATION: "Inhaled", INJECTION: "Injection", TOPICAL: "Applied to skin", OPHTHALMIC: "Eye drops", OTIC: "Ear drops" }; return map[route] || formatEnum(route); }
function inferRouteFromDosageForm(value: unknown): string { const form = String(value || "").trim().toLowerCase(); if (!form) return ""; if (/tablet|caplet|capsule|pill|chewable|lozenge|troche|sublingual|buccal|oral|syrup|solution|suspension|powder|granule|elixir/.test(form)) return "ORAL"; if (/inhaler|inhalation|nebul|aerosol/.test(form)) return "INHALATION"; if (/injection|injectable|vial|ampoule|prefilled syringe/.test(form)) return "INJECTION"; if (/cream|ointment|gel|lotion|paste|topical|transdermal|patch/.test(form)) return "TOPICAL"; if (/ophthalmic|eye drop|ocular/.test(form)) return "OPHTHALMIC"; if (/otic|ear drop/.test(form)) return "OTIC"; return ""; }
function getFormulationSummaries(m: any): string[] { const rows = Array.isArray(m?.strengths) ? m.strengths : []; return Array.from(new Set(rows.map((s: any) => { const rawStrength = String(s?.strength || "").trim(); const strength = /^(unspecified|unknown|n\/a|na|not specified)$/i.test(rawStrength) ? "" : rawStrength; const form = String(s?.dosageForm || "").trim(); const route = String(s?.route || "").trim().toUpperCase() || inferRouteFromDosageForm(form); return [strength, form, route ? formatRouteLabel(route) : ""].filter(Boolean).join(" · "); }).filter(Boolean))); }
function toItem(m: any): MedicationItem | null {
  const id = medicationId(m); if (!id) return null;
  return { patientMedicationId: String(id), medicationId: String(m?.medicationId || m?.medication?.id || ""), dosage: m?.dosage, frequency: m?.frequency, route: m?.route, indication: m?.indication, instructions: m?.instructions, prescribedBy: m?.prescribedBy, startedAt: m?.startedAt, endedAt: m?.endedAt, ongoing: m?.ongoing ?? (m?.status ? m.status === "ACTIVE" : true), adherencePercentage: m?.adherencePercentage, missedDoses: m?.missedDoses, sideEffects: m?.sideEffects, effectiveness: m?.effectiveness, status: m?.status, notes: m?.notes };
}
const emptyMedication = (): MedicationItem => ({ medicationId: "", dosage: "", frequency: "", route: "", prescribedBy: "", indication: "", instructions: "", startedAt: "", endedAt: "", ongoing: true, sideEffects: "", effectiveness: "", notes: "" });

function Field({ label, hint, optional, children }: { label: string; hint?: string; optional?: boolean; children: ReactNode }) {
  return <div><div className="mb-2 flex items-end justify-between gap-3"><label className="text-sm font-semibold text-[#0b2d54]">{label}</label>{optional && <span className="text-[11px] text-slate-400">Optional</span>}</div>{children}{hint && <p className="mt-1.5 text-[11px] leading-4 text-slate-400">{hint}</p>}</div>;
}
function Select({ value, onChange, options, placeholder, disabled }: { value: string; onChange: (v: string) => void; options: readonly (readonly [string, string])[] | string[]; placeholder: string; disabled?: boolean }) {
  return <div className="relative"><select disabled={disabled} value={value} onChange={e => onChange(e.target.value)} className="w-full appearance-none rounded-2xl border border-slate-200 bg-white px-4 py-3.5 pr-10 text-sm text-[#0b2d54] outline-none transition-all focus:border-[#24c1c4] focus:ring-4 focus:ring-[#24c1c4]/10 disabled:cursor-default disabled:bg-slate-50 disabled:text-[#0b2d54]"><option value="">{placeholder}</option>{options.map(o => Array.isArray(o) ? <option key={o[0]} value={o[0]}>{o[1]}</option> : <option key={o} value={o}>{o}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /></div>;
}
function TextInput({ value, onChange, placeholder }: { value: string; onChange: (v: string) => void; placeholder: string }) {
  return <input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 text-sm text-[#0b2d54] outline-none transition-all placeholder:text-slate-400 focus:border-[#24c1c4] focus:ring-4 focus:ring-[#24c1c4]/10" />;
}

function MedicationForm({ value, onChange }: { value: MedicationItem; onChange: (v: MedicationItem) => void }) {
  const [step, setStep] = useState(1);
  const [search, setSearch] = useState("");
  const [results, setResults] = useState<any[]>([]);
  const [searching, setSearching] = useState(false);
  const [selectedName, setSelectedName] = useState("");
  const [selectedMedication, setSelectedMedication] = useState<any | null>(null);
  const [custom, setCustom] = useState<Record<string, boolean>>({});

  async function searchMedication(term: string) {
    setSearch(term); setSelectedName(""); setSelectedMedication(null); onChange({ ...value, medicationId: "", dosage: "", route: "" });
    if (term.trim().length < 2) { setResults([]); return; }
    try { setSearching(true); const { data } = await api.get("/medications", { params: { search: term.trim(), limit: 10, page: 1 } }); setResults(Array.isArray(data?.data?.data) ? data.data.data : []); }
    catch { setResults([]); }
    finally { setSearching(false); }
  }
  const set = (key: keyof MedicationItem, val: any) => onChange({ ...value, [key]: val });
  const choose = (key: keyof MedicationItem, val: string) => { const other = val === "Other"; setCustom(c => ({ ...c, [String(key)]: other })); set(key, other ? "" : val); };

  const strengths = useMemo(() => { const rows = Array.isArray(selectedMedication?.strengths) ? selectedMedication.strengths : []; return Array.from(new Set(rows.map((s: any) => String(s?.strength || "").trim()).filter(v => v && !/^(unspecified|unknown|n\/a|na|not specified)$/i.test(v)))); }, [selectedMedication]);
  const routeCandidates = useMemo(() => { const rows = Array.isArray(selectedMedication?.strengths) ? selectedMedication.strengths : []; return Array.from(new Set(rows.map((s: any) => String(s?.route || "").trim().toUpperCase() || inferRouteFromDosageForm(s?.dosageForm)).filter(Boolean))); }, [selectedMedication]);
  const dosageForms = useMemo(() => { const rows = Array.isArray(selectedMedication?.strengths) ? selectedMedication.strengths : []; return Array.from(new Set(rows.map((s: any) => String(s?.dosageForm || "").trim()).filter(Boolean))); }, [selectedMedication]);
  const knownRoute = routeCandidates.length === 1 ? routeCandidates[0] : "";
  const routeLabel = knownRoute ? formatRouteLabel(knownRoute) : "";
  const doseOptions = strengths.length === 1 ? strengths : strengths.length > 1 ? [...strengths, "Other"] : DOSES;
  const routeIsKnown = Boolean(knownRoute);
  const canNext = step === 1 ? Boolean(value.medicationId && value.dosage && value.frequency && value.route) : step === 2 ? Boolean(value.indication && value.instructions && value.startedAt) : true;

  return <div className="space-y-6">
    <div className="flex items-center gap-2 px-1"><div className={`h-1.5 flex-1 rounded-full ${step >= 1 ? "bg-[#24c1c4]" : "bg-slate-100"}`} /><div className={`h-1.5 flex-1 rounded-full ${step >= 2 ? "bg-[#24c1c4]" : "bg-slate-100"}`} /><div className={`h-1.5 flex-1 rounded-full ${step >= 3 ? "bg-[#24c1c4]" : "bg-slate-100"}`} /></div>
    <div className="flex items-center justify-between px-1"><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-[#24c1c4]">Step {step} of 3</p><h3 className="mt-1 text-lg font-bold text-[#0b2d54]">{step === 1 ? "Choose your medicine" : step === 2 ? "Tell us how you use it" : "A few finishing touches"}</h3></div><span className="rounded-full bg-[#24c1c4]/10 px-3 py-1 text-[11px] font-semibold text-[#0b2d54]">Quick setup</span></div>

    {step === 1 && <div className="space-y-5 animate-in fade-in slide-in-from-right-2 duration-300">
      <div className="rounded-2xl border border-[#24c1c4]/20 bg-gradient-to-br from-[#24c1c4]/10 via-white to-white p-5">
        <Field label="Find your medicine" hint="Search by the name on your medicine box or prescription. Select the matching medicine and Sympto will fill in the details it already knows.">
          <div className="relative">
            <input value={selectedName || search} onChange={e => searchMedication(e.target.value)} disabled={Boolean(value.medicationId)} placeholder="e.g. Aspirin, Metformin, Paracetamol" className={`w-full rounded-2xl border px-4 py-3.5 pr-36 text-sm text-[#0b2d54] outline-none transition-all placeholder:text-slate-400 ${value.medicationId ? "border-[#24c1c4]/30 bg-slate-50 font-semibold shadow-sm disabled:cursor-default" : "border-slate-200 bg-white focus:border-[#24c1c4] focus:ring-4 focus:ring-[#24c1c4]/10"}`} />
            {value.medicationId && <span className="pointer-events-none absolute right-4 top-1/2 flex -translate-y-1/2 items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700"><Check className="h-3.5 w-3.5" />Medicine recognised</span>}
            {searching && !value.medicationId && <span className="absolute right-4 top-1/2 -translate-y-1/2 text-[11px] text-slate-400">Searching…</span>}
          </div>
          {value.medicationId && <div className="mt-2 flex items-center justify-between gap-3"><p className="text-[11px] text-slate-400">Selected from Sympto's medicine reference library.</p><button type="button" onClick={() => { setSelectedName(""); setSearch(""); setResults([]); setSelectedMedication(null); onChange({ ...value, medicationId: "", dosage: "", route: "" }); }} className="text-[11px] font-semibold text-[#0b2d54] hover:text-[#24c1c4]">Choose a different medicine</button></div>}
        {results.length > 0 && !value.medicationId && <div className="mt-2 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl shadow-slate-200/40">{results.map(r => { const formulations = getFormulationSummaries(r); const formulationRows = Array.isArray(r?.strengths) ? r.strengths : []; return <button key={r.id} type="button" onClick={() => {
          const strengthsForMedication = Array.isArray(r?.strengths) ? r.strengths : [];
          const uniqueStrengths = Array.from(new Set(strengthsForMedication.map((s: any) => String(s?.strength || "").trim()).filter(v => v && !/^(unspecified|unknown|n\/a|na|not specified)$/i.test(v))));
          const uniqueRoutes = Array.from(new Set(strengthsForMedication.map((s: any) => String(s?.route || "").trim().toUpperCase() || inferRouteFromDosageForm(s?.dosageForm)).filter(Boolean)));
          const autoRoute = uniqueRoutes.length === 1 ? uniqueRoutes[0] : "";
          setSelectedName(String(r.name)); setSearch(String(r.name)); setResults([]); setSelectedMedication(r);
          onChange({ ...value, medicationId: String(r.id), dosage: uniqueStrengths.length === 1 ? uniqueStrengths[0] : "", route: autoRoute });
        }} className="flex w-full items-start justify-between gap-4 border-b border-slate-100 px-4 py-4 text-left last:border-0 hover:bg-[#24c1c4]/5"><span className="min-w-0 flex-1"><span className="block text-sm font-bold text-[#0b2d54]">{r.name || "Medicine"}</span><span className="mt-2 grid gap-x-6 gap-y-1.5 text-[11px] leading-4 sm:grid-cols-2"><span><b className="text-[#0b2d54]">Generic name:</b> {r.genericName || "Not specified"}</span><span><b className="text-[#0b2d54]">Type of medicine:</b> {formatCategoryLabel(r.category)}</span></span>{formulationRows.length > 0 && <span className="mt-3 block rounded-xl bg-slate-50 px-3 py-2.5"><span className="block text-[10px] font-bold uppercase tracking-[0.12em] text-[#24c1c4]">Available options</span><span className="mt-1.5 block space-y-1.5">{formulationRows.map((s: any, index: number) => { const rawStrength = String(s?.strength || "").trim(); const strength = /^(unspecified|unknown|n\/a|na|not specified)$/i.test(rawStrength) ? "Not specified" : rawStrength; const form = formatDosageForm(s?.dosageForm); const route = String(s?.route || "").trim().toUpperCase() || inferRouteFromDosageForm(form); return <span key={`${s?.id || index}-${strength}-${form}-${route}`} className="block text-[11px] text-slate-600"><b className="text-[#0b2d54]">Strength:</b> {strength} <span className="mx-1 text-slate-300">·</span> <b className="text-[#0b2d54]">Form:</b> {form} <span className="mx-1 text-slate-300">·</span> <b className="text-[#0b2d54]">How you take it:</b> {route ? formatRouteLabel(route) : "Not specified"}</span>; })}</span></span>}{formulationRows.length === 0 && formulations.length > 0 && <span className="mt-3 block text-[11px] font-medium text-slate-500">{formulations.join(" / ")}</span>}</span><Plus className="mt-1 h-4 w-4 shrink-0 text-[#24c1c4]" /></button>})}</div>}
          {value.medicationId && <div className="mt-4 rounded-2xl border border-[#24c1c4]/15 bg-white p-4 shadow-sm"><div className="flex items-start gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-[#24c1c4]/10 text-[#0b2d54]"><Check className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-[#0b2d54]">Medicine details filled in</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">Generic name</p><p className="mt-1 text-sm font-semibold text-[#0b2d54]">{selectedMedication?.genericName || "Not specified"}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">Type of medicine</p><p className="mt-1 text-sm font-semibold text-[#0b2d54]">{formatCategoryLabel(selectedMedication?.category)}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">Medicine form</p><p className="mt-1 text-sm font-semibold text-[#0b2d54]">{dosageForms.length ? dosageForms.map(formatDosageForm).join(" / ") : "Not specified"}</p></div><div><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">How you take it</p><p className="mt-1 text-sm font-semibold text-[#0b2d54]">{routeIsKnown ? routeLabel : "Choose below"}</p></div></div>{routeIsKnown && <p className="mt-3 text-[11px] font-semibold text-emerald-700">✓ How you take it was recognised automatically.</p>}</div></div></div>}
        </Field>
      </div>
      <div className="grid gap-4 sm:grid-cols-2">
        <Field label="Strength / dose" hint={strengths.length ? "Choose from the strengths available for this medicine." : "No specific strength is recorded. Choose the dose you use."}><Select value={custom.dosage ? "Other" : value.dosage || ""} onChange={v => choose("dosage", v)} options={doseOptions} placeholder={strengths.length ? "Select strength" : "Select your dose"} disabled={strengths.length === 1 && Boolean(value.dosage)} />{custom.dosage && <div className="mt-2"><TextInput value={value.dosage || ""} onChange={v => set("dosage", v)} placeholder="e.g. 125 mg" /></div>}</Field>
        <Field label="How often do you take it?"><Select value={value.frequency || ""} onChange={v => set("frequency", v)} options={FREQUENCIES} placeholder="Choose a schedule" /></Field>
      </div>
      {!routeIsKnown && <Field label="How do you take it?" hint="Choose how this medicine is used."><Select value={value.route || ""} onChange={v => set("route", v)} options={ROUTES} placeholder="Choose how you take it" /></Field>}
      {routeIsKnown && <div className="flex items-center gap-3 rounded-2xl border border-[#24c1c4]/15 bg-[#0b2d54]/[0.03] px-4 py-3"><ShieldCheck className="h-4 w-4 shrink-0 text-[#24c1c4]" /><div className="text-xs text-slate-500"><b className="text-[#0b2d54]">How you take it: {routeLabel}</b> · Sympto recognised this from the medicine formulation.</div></div>}
    </div>}

    {step === 2 && <div className="grid gap-5 sm:grid-cols-2 animate-in fade-in slide-in-from-right-2 duration-300">
      <Field label="What are you taking it for?" hint="This helps Sympto understand your treatment context."><Select value={custom.indication ? "Other" : value.indication || ""} onChange={v => choose("indication", v)} options={REASONS} placeholder="Choose a reason" />{custom.indication && <div className="mt-2"><TextInput value={value.indication || ""} onChange={v => set("indication", v)} placeholder="What are you treating?" /></div>}</Field>
      <Field label="What instructions were you given?" hint="Use the instructions on your prescription or from your healthcare professional."><Select value={custom.instructions ? "Other" : value.instructions || ""} onChange={v => choose("instructions", v)} options={INSTRUCTIONS} placeholder="Choose an instruction" />{custom.instructions && <div className="mt-2"><TextInput value={value.instructions || ""} onChange={v => set("instructions", v)} placeholder="e.g. Take 1 tablet after breakfast" /></div>}</Field>
      <Field label="When did you start?" hint="When did you start taking this medicine?"><input type="date" value={value.startedAt ? String(value.startedAt).slice(0, 10) : ""} onChange={e => set("startedAt", e.target.value || undefined)} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 text-sm text-[#0b2d54] outline-none focus:border-[#24c1c4] focus:ring-4 focus:ring-[#24c1c4]/10" /></Field>
      <div className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-semibold text-[#0b2d54]">I currently take this medicine</p><p className="mt-1 text-xs text-slate-500">Keep it active in Today and your health goals.</p></div><button type="button" onClick={() => set("ongoing", !(value.ongoing !== false))} className={`relative h-7 w-12 rounded-full transition-colors ${value.ongoing !== false ? "bg-[#24c1c4]" : "bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition-transform ${value.ongoing !== false ? "left-6" : "left-1"}`} /></button></div></div>
      {value.ongoing === false && <Field label="When did you stop?"><input type="date" value={value.endedAt ? String(value.endedAt).slice(0, 10) : ""} onChange={e => set("endedAt", e.target.value || undefined)} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3.5 text-sm text-[#0b2d54] outline-none focus:border-[#24c1c4] focus:ring-4 focus:ring-[#24c1c4]/10" /></Field>}
    </div>}

    {step === 3 && <div className="space-y-5 animate-in fade-in slide-in-from-right-2 duration-300">
      <div className="rounded-2xl border border-[#24c1c4]/15 bg-[#24c1c4]/5 p-4"><div className="flex gap-3"><Sparkles className="h-5 w-5 shrink-0 text-[#24c1c4]" /><div><p className="text-sm font-semibold text-[#0b2d54]">Almost there</p><p className="mt-1 text-xs leading-5 text-slate-500">These details help Sympto personalise reminders and your medication health journey. Skip anything you do not know.</p></div></div></div>
      <div className="grid gap-5 sm:grid-cols-2">
        <Field label="Who prescribed or recommended it?" optional><Select value={custom.prescribedBy ? "Other" : value.prescribedBy || ""} onChange={v => choose("prescribedBy", v)} options={PRESCRIBERS} placeholder="Choose a provider" />{custom.prescribedBy && <div className="mt-2"><TextInput value={value.prescribedBy || ""} onChange={v => set("prescribedBy", v)} placeholder="Doctor, clinic or provider name" /></div>}</Field>
        <Field label="Have you noticed any side effects?" optional><Select value={custom.sideEffects ? "Other" : value.sideEffects || ""} onChange={v => choose("sideEffects", v)} options={SIDE_EFFECTS} placeholder="Choose what you noticed" />{custom.sideEffects && <div className="mt-2"><TextInput value={value.sideEffects || ""} onChange={v => set("sideEffects", v)} placeholder="Describe what you noticed" /></div>}</Field>
        <Field label="How is the medicine working?" optional><Select value={value.effectiveness || ""} onChange={v => set("effectiveness", v)} options={EFFECTIVENESS} placeholder="Choose an option" /></Field>
        <Field label="Anything else to remember?" optional hint="Add anything else you want Sympto to remember."><textarea value={value.notes || ""} onChange={e => set("notes", e.target.value)} rows={3} placeholder="e.g. I take this with my morning routine" className="w-full resize-none rounded-2xl border border-slate-200 bg-white px-4 py-3.5 text-sm text-[#0b2d54] outline-none placeholder:text-slate-400 focus:border-[#24c1c4] focus:ring-4 focus:ring-[#24c1c4]/10" /></Field>
      </div>
    </div>}

    <div className="flex items-center justify-between border-t border-slate-100 pt-5"><button type="button" onClick={() => setStep(s => Math.max(1, s - 1))} disabled={step === 1} className="rounded-xl px-3 py-2 text-sm font-semibold text-slate-500 disabled:invisible hover:text-[#0b2d54]">Back</button><div className="flex items-center gap-3"><span className="hidden text-xs text-slate-400 sm:block">{step === 3 ? "Review your details before saving" : "You can update this later"}</span>{step < 3 ? <Button type="button" disabled={!canNext} onClick={() => setStep(s => s + 1)} className="rounded-xl bg-[#0b2d54] px-5 text-white shadow-sm hover:bg-[#071f3a]">Continue</Button> : null}</div></div>
  </div>;
}

export default function MedicationsPage() {
  const { data, loading, error, reload } = useDashboard();
  const [showEditor, setShowEditor] = useState(false);
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const medications = Array.isArray(data?.medications) && data.medications.length ? data.medications : (data?.today?.activeMedications ?? []);
  const active = medications.filter((m: any) => m?.ongoing === true || m?.status === "ACTIVE" || !m?.status);
  const initial = useMemo<UpdatePatientMedicationsDto>(() => ({ medications: medications.filter((m: any) => m?.source !== "PRESCRIPTION").map(toItem).filter(Boolean) as MedicationItem[] }), [medications]);
  const [values, setValues] = useState<UpdatePatientMedicationsDto>({ medications: [] });
  function openAdd() { setValues({ medications: [emptyMedication()] }); setEditing(false); setShowEditor(true); }
  function openEdit() { setValues(initial); setEditing(true); setShowEditor(true); }
  async function save() {
    if (saving) return; const valid = values.medications.filter(m => m.medicationId);
    if (!valid.length) { toast.error("Please select a medicine first."); return; }
    try { setSaving(true); const saveList = editing ? valid : [...initial.medications, ...valid.filter(n => !initial.medications.some(e => e.medicationId === n.medicationId))]; await onboardingService.managePatientMedications({ medications: saveList }); toast.success("Medicine saved"); setShowEditor(false); await reload(); }
    catch (e: any) { const msg = e?.response?.data?.message; toast.error(Array.isArray(msg) ? msg.join(", ") : msg || "Unable to save your medicine."); }
    finally { setSaving(false); }
  }
  return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-medium text-[#0b2d54] hover:text-[#24c1c4]"><ArrowLeft className="h-4 w-4" />Back to Health Home</Link><Button onClick={openAdd} className="rounded-xl bg-[#0b2d54] px-4 text-white shadow-sm hover:bg-[#071f3a]"><Plus className="mr-2 h-4 w-4" />Add medicine</Button></div>
    <div className="mb-8"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[#24c1c4]/10 px-3 py-1 text-xs font-semibold text-[#0b2d54]"><Pill className="h-3.5 w-3.5" />My health</div><h1 className="text-3xl font-bold tracking-tight text-[#0b2d54] sm:text-4xl">Medications</h1><p className="mt-2 max-w-2xl text-slate-500">Keep track of your current medicines, doses, schedules and prescribing information.</p></div>
    {loading && <div className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-500">Loading your medications…</div>}
    {error && !loading && <div className="mb-6 rounded-2xl border border-red-200 bg-white p-6"><h2 className="font-semibold text-[#0b2d54]">We couldn't load your medications</h2><button onClick={reload} className="mt-4 rounded-xl bg-[#0b2d54] px-4 py-2 text-sm font-semibold text-white">Try again</button></div>}
    {showEditor && <section className="mb-8 overflow-hidden rounded-[28px] border border-[#24c1c4]/15 bg-white shadow-2xl shadow-[#0b2d54]/10"><div className="bg-gradient-to-br from-[#0b2d54] via-[#103966] to-[#0b2d54] px-5 py-7 text-white sm:px-8"><div className="flex items-start justify-between gap-5"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-[11px] font-semibold text-[#b9ffff]"><Sparkles className="h-3.5 w-3.5" />Sympto medication setup</div><h2 className="text-2xl font-bold tracking-tight">{editing ? "Update your medication" : "Add a medication"}</h2><p className="mt-1.5 max-w-xl text-sm leading-6 text-slate-200">Choose your medicine and Sympto will fill in the details it already knows. You only add your personal treatment information.</p></div><button type="button" disabled={saving} onClick={() => setShowEditor(false)} className="rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-semibold text-white hover:bg-white/10">Close</button></div></div><div className="px-5 py-7 sm:px-8 lg:px-12"><MedicationForm value={values.medications[0] || emptyMedication()} onChange={next => setValues({ medications: [next] })} /></div><div className="flex flex-col gap-3 border-t border-slate-100 bg-slate-50/70 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-8"><p className="text-xs text-slate-400">Your medication details stay part of your Sympto health profile.</p><div className="flex gap-3"><Button variant="outline" disabled={saving} onClick={() => setShowEditor(false)} className="rounded-xl text-[#0b2d54]">Cancel</Button><Button disabled={saving || !values.medications[0]?.medicationId} onClick={save} className="rounded-xl bg-[#0b2d54] px-6 text-white shadow-sm hover:bg-[#071f3a]">{saving ? "Saving…" : "Save medication"}</Button></div></div></section>}
    <section className="mb-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Pill className="h-5 w-5 text-[#24c1c4]" /><p className="mt-4 text-2xl font-bold text-[#0b2d54]">{active.length}</p><p className="mt-1 text-sm text-slate-500">Current medications</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><Clock3 className="h-5 w-5 text-[#24c1c4]" /><p className="mt-4 text-2xl font-bold text-[#0b2d54]">{active.length}</p><p className="mt-1 text-sm text-slate-500">Active treatment plans</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><FileText className="h-5 w-5 text-[#24c1c4]" /><p className="mt-4 text-2xl font-bold text-[#0b2d54]">{medications.length}</p><p className="mt-1 text-sm text-slate-500">Medication records</p></div></section>
    {!loading && !error && <section><div className="mb-4 flex items-end justify-between gap-3"><div><h2 className="text-lg font-semibold text-[#0b2d54]">Current medications</h2><p className="mt-1 text-sm text-slate-500">Medicines currently recorded in your Sympto health profile.</p></div>{medications.length > 0 && <Button variant="outline" onClick={openEdit} className="rounded-xl border-[#0b2d54]/20 text-[#0b2d54]">Edit medications</Button>}</div>{active.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-200 bg-white p-10 text-center"><Pill className="mx-auto h-8 w-8 text-slate-300" /><h3 className="mt-4 font-semibold text-[#0b2d54]">No current medications</h3><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">Add a medicine so Sympto can connect it to your profile, reminders and medication goals.</p><Button onClick={openAdd} className="mt-5 rounded-xl bg-[#0b2d54] text-white"><Plus className="mr-2 h-4 w-4" />Add medicine</Button></div> : <div className="grid gap-4 md:grid-cols-2">{active.map((m: any) => { const name = String(m?.medication?.name || m?.medication?.genericName || m?.name || "Medication"); const dose = String(m?.dosage ?? "Not specified"); const id = medicationId(m); return <article key={String(m?.id ?? name)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:shadow-md"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#24c1c4]/10 text-[#0b2d54]"><Pill className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-[#0b2d54]">{name}</h3><span className="rounded-full bg-[#24c1c4]/10 px-2.5 py-1 text-[11px] font-semibold text-[#0b2d54]">{m?.source === "PRESCRIPTION" ? "Clinic prescription" : "My medication"}</span></div><span className="mt-2 inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700">Active</span><div className="mt-4 space-y-2 text-sm text-slate-600"><p><b>Strength / dose:</b> {dose}</p><p><b>How often:</b> {formatEnum(m?.frequency)}</p>{m?.route && <p><b>How you take it:</b> {formatRouteLabel(m.route)}</p>}{m?.indication && <p><b>What it's for:</b> {m.indication}</p>}{m?.instructions && <p><b>Instructions:</b> {m.instructions}</p>}{m?.prescribedBy && <p><b>Provider:</b> {m.prescribedBy}</p>}</div>{id && <MedicationAdherenceActions medicationId={String(id)} medicationName={name} adherencePercentage={m?.adherencePercentage} />}{id && <MedicationReminderButton medicationId={String(id)} medicationName={name} dosage={dose} />}</div></div></article>; })}</div>}</section>}
    <div className="mt-8 rounded-2xl border border-[#24c1c4]/20 bg-[#24c1c4]/5 p-5"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-[#0b2d54]" /><div><h3 className="font-semibold text-[#0b2d54]">Your medication details work together</h3><p className="mt-1 text-sm leading-6 text-slate-500">Sympto uses your medication information for your health profile, reminders, Today tracking and medication goals.</p></div></div></div>
  </div></main>;
}
