"use client";

import Link from "next/link";
import { ArrowLeft, FileText, FolderOpen, Plus, ShieldCheck, Upload } from "lucide-react";

export default function HealthRecordsPage() {
  return <main className="min-h-screen bg-[#F7F9FC]"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-medium text-[#0B5CAD] hover:underline"><ArrowLeft className="h-4 w-4" />Back to dashboard</Link><Link href="/health-passport" className="inline-flex items-center gap-2 rounded-xl bg-[#0B2D54] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#092541]"><FileText className="h-4 w-4" />Open Health Passport</Link></div>
    <div className="mb-8"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[#EAF3FB] px-3 py-1 text-xs font-semibold text-[#0B5CAD]"><FileText className="h-3.5 w-3.5" />My health</div><h1 className="text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Health records</h1><p className="mt-2 max-w-2xl text-slate-500">Keep your important healthcare information organised and use the linked health areas below to manage the records already supported by Sympto.</p></div>
    <div className="mb-8 grid gap-3 sm:grid-cols-2"><Link href="/health-conditions" className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-[#0B5CAD]/30 hover:shadow-sm"><h2 className="font-semibold text-slate-900">Allergies & conditions</h2><p className="mt-1 text-sm text-slate-500">Review and manage recorded allergies and active conditions.</p></Link><Link href="/medications" className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-[#0B5CAD]/30 hover:shadow-sm"><h2 className="font-semibold text-slate-900">Medications</h2><p className="mt-1 text-sm text-slate-500">Review current medicines, doses and reminders.</p></Link><Link href="/health-goals" className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-[#0B5CAD]/30 hover:shadow-sm"><h2 className="font-semibold text-slate-900">Health goals</h2><p className="mt-1 text-sm text-slate-500">Review active goals and progress.</p></Link><Link href="/emergency-contacts" className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-[#0B5CAD]/30 hover:shadow-sm"><h2 className="font-semibold text-slate-900">Emergency contacts</h2><p className="mt-1 text-sm text-slate-500">Keep important contacts available for urgent situations.</p></Link></div>
    <section className="mb-8"><h2 className="mb-4 text-lg font-semibold text-slate-900">Record categories</h2><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><FileText className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-slate-900">Clinical records</h3><p className="mt-1 text-sm leading-6 text-slate-500">Consultations, clinical notes, diagnoses and other healthcare records.</p><Link href="/appointments" className="mt-4 inline-flex text-sm font-semibold text-[#0B5CAD] hover:underline">View appointments</Link></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><FolderOpen className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-slate-900">Medical documents</h3><p className="mt-1 text-sm leading-6 text-slate-500">Use your Health Passport for structured clinical information while document storage is being connected.</p><Link href="/health-passport" className="mt-4 inline-flex text-sm font-semibold text-[#0B5CAD] hover:underline">View structured health data</Link></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><Upload className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-slate-900">Uploaded documents</h3><p className="mt-1 text-sm leading-6 text-slate-500">Document upload is not yet connected to a records API, so these controls no longer pretend to save data.</p><span className="mt-4 inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500">Storage integration pending</span></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white"><div className="flex flex-col items-center justify-center px-6 py-14 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-slate-100 text-slate-500"><FileText className="h-8 w-8" /></div><h2 className="mt-5 text-lg font-semibold text-slate-900">Your connected health record</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Use Health Passport and the linked sections above for the patient data currently supported by the application.</p><Link href="/health-passport" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#0B2D54] px-5 py-3 text-sm font-semibold text-white hover:bg-[#092541]"><Plus className="h-4 w-4" />Open Health Passport</Link></div></section>
    <div className="mt-8 flex items-center justify-center gap-2 pb-6 text-center text-xs text-slate-400"><ShieldCheck className="h-4 w-4" />Your health information is private and protected.</div>
  </div></main>;
}
