"use client";

import Link from "next/link";
import { ArrowLeft, FileText, FolderOpen, Plus, ShieldCheck, Upload, ClipboardCheck, ArrowRightLeft, FlaskConical, ScanLine, ShieldAlert } from "lucide-react";

const card = 'rounded-2xl border border-slate-200 bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#24c1c4]/50 hover:shadow-sm';

export default function HealthRecordsPage() {
  return <main className="min-h-screen bg-[#F7F9FC]"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-medium text-[#0B2D54] hover:text-[#24c1c4]"><ArrowLeft className="h-4 w-4" />Back to Health Home</Link><Link href="/health-passport" className="inline-flex items-center gap-2 rounded-xl bg-[#0B2D54] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#092541]"><FileText className="h-4 w-4" />Open Health Passport</Link></div>
    <div className="mb-8"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[#24c1c4]/10 px-3 py-1 text-xs font-semibold text-[#0B2D54]"><FileText className="h-3.5 w-3.5" />My health</div><h1 className="text-3xl font-bold tracking-tight text-[#0B2D54] sm:text-4xl">Health records</h1><p className="mt-2 max-w-2xl text-slate-500">Your clinical history, results, care coordination and structured health information — connected to the same patient record.</p></div>
    <div className="mb-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Link href="/health-conditions" className={card}><h2 className="font-semibold text-[#0B2D54]">Allergies & conditions</h2><p className="mt-1 text-sm text-slate-500">Review recorded allergies and active conditions.</p></Link><Link href="/medications" className={card}><h2 className="font-semibold text-[#0B2D54]">Medications</h2><p className="mt-1 text-sm text-slate-500">Review medicines, doses and reminders.</p></Link><Link href="/health-goals" className={card}><h2 className="font-semibold text-[#0B2D54]">Health goals</h2><p className="mt-1 text-sm text-slate-500">Review active and completed goals.</p></Link><Link href="/emergency-contacts" className={card}><h2 className="font-semibold text-[#0B2D54]">Emergency contacts</h2><p className="mt-1 text-sm text-slate-500">Keep trusted contacts available.</p></Link></div>
    <section className="mb-8"><h2 className="mb-4 text-lg font-semibold text-[#0B2D54]">Clinical record</h2><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Link href="/care-plans" className={card}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#24c1c4]/10 text-[#0B2D54]"><ClipboardCheck className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-[#0B2D54]">Care plans</h3><p className="mt-1 text-sm leading-6 text-slate-500">See clinician-created goals and care tasks.</p></Link><Link href="/referrals" className={card}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#24c1c4]/10 text-[#0B2D54]"><ArrowRightLeft className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-[#0B2D54]">Referrals</h3><p className="mt-1 text-sm leading-6 text-slate-500">Track referrals and follow-up feedback.</p></Link><Link href="/lab-results" className={card}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#24c1c4]/10 text-[#0B2D54]"><FlaskConical className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-[#0B2D54]">Laboratory results</h3><p className="mt-1 text-sm leading-6 text-slate-500">Review released test results and flagged values.</p></Link><Link href="/imaging" className={card}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#24c1c4]/10 text-[#0B2D54]"><ScanLine className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-[#0B2D54]">Imaging & scans</h3><p className="mt-1 text-sm leading-6 text-slate-500">Review scans and available clinical reports.</p></Link><Link href="/risk-assessments" className={card}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#0B2D54]/5 text-[#0B2D54]"><ShieldAlert className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-[#0B2D54]">Risk assessments</h3><p className="mt-1 text-sm leading-6 text-slate-500">Review recorded preventive risk assessments.</p></Link><Link href="/appointments" className={card}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><FileText className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-[#0B2D54]">Appointments</h3><p className="mt-1 text-sm leading-6 text-slate-500">See upcoming care and clinician visits.</p></Link></div></section>
    <section className="mb-8 grid gap-4 md:grid-cols-2"><div className={card}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><FolderOpen className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-[#0B2D54]">Structured health data</h3><p className="mt-1 text-sm leading-6 text-slate-500">Your Health Passport remains the source for structured identity, blood information, allergies, conditions and immunizations.</p><Link href="/health-passport" className="mt-4 inline-flex text-sm font-semibold text-[#0B2D54] hover:text-[#24c1c4]">Open Health Passport →</Link></div><div className={card}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><Upload className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-[#0B2D54]">Uploaded documents</h3><p className="mt-1 text-sm leading-6 text-slate-500">Document storage is not yet connected to a patient-facing upload API, so Sympto does not pretend this control saves anything.</p><span className="mt-4 inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500">Storage integration pending</span></div></section>
    <section className="rounded-2xl border border-[#24c1c4]/20 bg-[#24c1c4]/5 p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#0B2D54]" /><div><h2 className="font-semibold text-[#0B2D54]">One connected patient record</h2><p className="mt-1 text-sm leading-6 text-slate-600">These pages read from the authenticated patient's records. You should never need to enter the same clinical information in multiple places.</p></div></div></section>
  </div></main>;
}
