"use client";

import Link from "next/link";
import { ArrowLeft, CalendarDays, CheckCircle2, Pill, Sparkles, Target, TriangleAlert } from "lucide-react";
import ProtectedRoute from "@/components/auth/protected-route";
import { useDashboard } from "@/hooks/use-dashboard";

function formatDate(value: unknown) { if (!value) return "—"; const date = new Date(String(value)); if (Number.isNaN(date.getTime())) return String(value); return new Intl.DateTimeFormat("en-ZA", { dateStyle: "medium", timeStyle: "short" }).format(date); }
function text(value: unknown, fallback = "—") { return value === null || value === undefined || value === "" ? fallback : String(value); }

export default function TodayPage() {
  const { data, loading, error, reload } = useDashboard();
  if (loading) return <ProtectedRoute><main className="min-h-screen bg-[#f5f8fb] p-4 sm:p-8"><div className="mx-auto max-w-3xl animate-pulse space-y-4"><div className="h-28 rounded-[28px] bg-white"/><div className="h-48 rounded-[28px] bg-white"/><div className="h-48 rounded-[28px] bg-white"/></div></main></ProtectedRoute>;
  if (error || !data) return <ProtectedRoute><main className="min-h-screen bg-[#f5f8fb] p-4 sm:p-8"><div className="mx-auto max-w-xl rounded-[28px] border border-red-200 bg-white p-7"><TriangleAlert className="h-6 w-6 text-red-600"/><h1 className="mt-4 text-xl font-bold text-[#0b2d54]">We couldn't load today</h1><p className="mt-2 text-sm text-slate-500">Your saved information has not been changed.</p><button onClick={reload} className="mt-5 rounded-xl bg-[#0b2d54] px-5 py-2.5 text-sm font-semibold text-white">Try again</button></div></main></ProtectedRoute>;
  const medications = data.today?.activeMedications ?? [];
  const appointments = data.today?.upcomingAppointments ?? [];
  const goals = (data.goals ?? []).filter((goal) => String(goal.status).toUpperCase() !== "ACHIEVED");
  const attention = data.attention ?? [];
  const notifications = data.today?.notifications ?? data.notifications ?? [];
  const aiObservations = data.ai?.recentObservations ?? [];
  const firstName = data.patient?.firstName || data.profile?.preferredName || "there";
  return <ProtectedRoute><main className="min-h-screen bg-[#f5f8fb]"><header className="border-b border-slate-200/80 bg-white"><div className="mx-auto flex h-16 max-w-3xl items-center px-4 sm:px-6"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-[#0b2d54]"><ArrowLeft className="h-4 w-4"/>My Health</Link></div></header><div className="mx-auto max-w-3xl px-4 py-7 sm:px-6">
    <section className="rounded-[28px] bg-gradient-to-br from-[#0b2d54] to-[#24c1c4] p-7 text-white shadow-[0_18px_45px_rgba(11,45,84,0.14)] sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.18em] text-white/70">Today</p><h1 className="mt-3 text-3xl font-bold">Hi {text(firstName, "there")}</h1><p className="mt-2 text-sm leading-6 text-white/80">Here is what matters today. Sympto has organised it for you.</p></section>
    {attention.length > 0 && <section className="mt-5 rounded-[24px] border border-amber-200 bg-amber-50 p-5"><div className="flex items-center gap-3"><TriangleAlert className="h-5 w-5 text-amber-700"/><h2 className="font-bold text-amber-900">Needs your attention</h2></div><div className="mt-4 space-y-3">{attention.map((item, index) => <div key={`${item.type}-${index}`} className="rounded-2xl bg-white/70 p-4"><p className="text-sm font-bold text-[#0b2d54]">{text(item.title)}</p><p className="mt-1 text-sm leading-5 text-slate-600">{text(item.description)}</p>{item.actionUrl && <Link href={String(item.actionUrl)} className="mt-2 inline-block text-xs font-bold text-[#0b2d54] underline">{text(item.actionLabel, "Open")}</Link>}</div>)}</div></section>}
    <section className="mt-5 rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#24c1c4]/10 text-[#0b2d54]"><Pill className="h-5 w-5"/></span><div><h2 className="font-bold text-[#0b2d54]">Medicine</h2><p className="text-xs text-slate-400">Your active medicines</p></div></div>{medications.length === 0 ? <p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Nothing to take has been recorded.</p> : <div className="mt-5 space-y-3">{medications.map((medication, index) => <div key={String(medication.id ?? index)} className="flex items-center justify-between gap-4 rounded-2xl bg-[#f7fafc] p-4"><div><p className="text-sm font-bold text-[#0b2d54]">{text(medication.medication?.name || medication.name || medication.medicationName, "Medicine")}</p><p className="mt-1 text-xs text-slate-500">{text(medication.dosage, "Dose not recorded")}{medication.frequency ? ` · ${String(medication.frequency)}` : ""}{medication.instructions ? ` · ${String(medication.instructions)}` : ""}</p></div><CheckCircle2 className="h-5 w-5 text-[#24c1c4]"/></div>)}</div>}<Link href="/medications" className="mt-4 inline-block text-xs font-bold text-[#0b2d54] underline">Open medicines</Link></section>
    <section className="mt-5 rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-700"><CalendarDays className="h-5 w-5"/></span><div><h2 className="font-bold text-[#0b2d54]">Clinic visits</h2><p className="text-xs text-slate-400">Upcoming appointments</p></div></div>{appointments.length === 0 ? <p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">No upcoming visit is scheduled.</p> : <div className="mt-5 space-y-3">{appointments.slice(0,5).map((appointment, index) => <div key={String(appointment.id ?? index)} className="rounded-2xl bg-[#f7fafc] p-4"><p className="text-sm font-bold text-[#0b2d54]">{text(appointment.title || appointment.type, "Clinic visit")}</p><p className="mt-1 text-xs text-slate-500">{formatDate(appointment.scheduledStart)}</p></div>)}</div>}<Link href="/appointments" className="mt-4 inline-block text-xs font-bold text-[#0b2d54] underline">Open visits</Link></section>
    <section className="mt-5 rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-violet-50 text-violet-700"><Target className="h-5 w-5"/></span><div><h2 className="font-bold text-[#0b2d54]">Care plans & goals</h2><p className="text-xs text-slate-400">Your active care work</p></div></div>{goals.length === 0 ? <p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">No active goals right now.</p> : <div className="mt-5 space-y-3">{goals.slice(0,4).map((goal, index) => <div key={String(goal.id ?? index)} className="rounded-2xl bg-[#f7fafc] p-4"><p className="text-sm font-bold text-[#0b2d54]">{text(goal.title, "Care goal")}</p><p className="mt-1 text-xs text-slate-500">{text(goal.category, "Care goal")}{goal.targetDate ? ` · Due ${formatDate(goal.targetDate)}` : ""}</p></div>)}</div>}<Link href="/health-goals" className="mt-4 inline-block text-xs font-bold text-[#0b2d54] underline">Open goals</Link></section>
    <section className="mt-5 rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#24c1c4]/10 text-[#0b2d54]"><Sparkles className="h-5 w-5"/></span><div><h2 className="font-bold text-[#0b2d54]">Sympto health helper</h2><p className="text-xs text-slate-400">Insights from your saved health information</p></div></div>{aiObservations.length ? <div className="mt-5 space-y-3">{aiObservations.slice(0,3).map((observation: any, index) => <div key={String(observation.id ?? index)} className="rounded-2xl bg-[#f7fafc] p-4"><p className="text-sm font-semibold text-[#0b2d54]">{text(observation.observation, "Health insight recorded")}</p>{observation.requiresAttention && <p className="mt-1 text-xs font-semibold text-amber-700">Needs review</p>}</div>)}</div> : <p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">No new AI health insight is recorded right now.</p>}</section>
    {notifications.length > 0 && <section className="mt-5 rounded-[24px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold text-[#0b2d54]">Reminders & notifications</h2><div className="mt-4 space-y-2">{notifications.slice(0,5).map((n: any) => <div key={String(n.id)} className="rounded-2xl bg-slate-50 p-4"><p className="text-sm font-semibold text-[#0b2d54]">{text(n.title)}</p><p className="mt-1 text-xs text-slate-500">{text(n.body)}</p></div>)}</div></section>}
  </div></main></ProtectedRoute>;
}
