"use client";

import Link from "next/link";
import { ArrowLeft, CalendarDays, Clock3, MapPin, Stethoscope } from "lucide-react";
import ProtectedRoute from "@/components/auth/protected-route";
import { useDashboard } from "@/hooks/use-dashboard";

function formatDate(value: unknown) { if (!value) return "Date not recorded"; const date = new Date(String(value)); if (Number.isNaN(date.getTime())) return String(value); return new Intl.DateTimeFormat("en-ZA", { dateStyle: "full", timeStyle: "short" }).format(date); }
function value(obj: any, ...keys: string[]) { for (const key of keys) if (obj?.[key]) return obj[key]; return null; }

export default function AppointmentsPage() {
  const { data, loading, error, reload } = useDashboard();
  const appointments = data?.appointments ?? data?.today?.upcomingAppointments ?? [];
  return <ProtectedRoute><main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
    <Link href="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm font-medium text-[#0b2d54] hover:text-[#24c1c4]"><ArrowLeft className="h-4 w-4" /> Back to Health Home</Link>
    <div className="mb-8"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[#24c1c4]/10 px-3 py-1 text-xs font-semibold text-[#0b2d54]"><CalendarDays className="h-3.5 w-3.5" /> Appointments</div><h1 className="text-3xl font-bold tracking-tight text-[#0b2d54] sm:text-4xl">Your appointments</h1><p className="mt-2 max-w-2xl text-slate-500">Your upcoming healthcare appointments from your Sympto health record.</p></div>
    {loading && <div className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">Loading your appointments…</div>}
    {error && !loading && <div className="rounded-2xl border border-red-200 bg-white p-6"><h2 className="font-semibold text-[#0b2d54]">We couldn't load your appointments</h2><button onClick={reload} className="mt-4 rounded-xl bg-[#0b2d54] px-4 py-2 text-sm font-semibold text-white">Try again</button></div>}
    {!loading && !error && appointments.length === 0 && <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#24c1c4]/10 text-[#0b2d54]"><Stethoscope className="h-7 w-7" /></div><h2 className="mt-5 text-xl font-semibold text-[#0b2d54]">No upcoming appointments</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">When appointments are recorded for you, they will appear here automatically.</p></div>}
    {!loading && !error && appointments.length > 0 && <div className="space-y-4">{appointments.map((appointment: any) => { const practitioner = appointment?.practitioner?.person; const practitionerName = practitioner ? [practitioner.firstName, practitioner.lastName].filter(Boolean).join(" ") : null; const practice = appointment?.practice?.name; return <article key={appointment.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-5 sm:flex-row sm:items-start"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[#24c1c4]/10 text-[#0b2d54]"><CalendarDays className="h-6 w-6" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold text-[#0b2d54]">{value(appointment, "title", "type") || "Healthcare appointment"}</h2>{appointment.status && <span className="rounded-full bg-[#24c1c4]/10 px-2.5 py-1 text-[11px] font-semibold text-[#0b2d54]">{String(appointment.status).replace(/_/g, " ")}</span>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center gap-2 text-xs font-medium text-slate-400"><Clock3 className="h-4 w-4" /> Date & time</div><p className="mt-1 text-sm font-semibold text-[#0b2d54]">{formatDate(appointment.scheduledStart)}</p></div>{(practitionerName || practice) && <div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center gap-2 text-xs font-medium text-slate-400"><MapPin className="h-4 w-4" /> Care</div><p className="mt-1 text-sm font-semibold text-[#0b2d54]">{practitionerName || practice}</p>{practitionerName && practice && <p className="mt-1 text-xs text-slate-500">{practice}</p>}</div>}</div></div></div></article>; })}</div>}
  </div></main></ProtectedRoute>;
}
