"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import type { ReactNode } from "react";
import { useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, FolderOpen, HeartPulse, Pill, ShieldCheck, TriangleAlert, Watch, Weight } from "lucide-react";
import ProtectedRoute from "@/components/auth/protected-route";
import { useDashboard } from "@/hooks/use-dashboard";
import { healthHomeService } from "@/services/health-home.service";

function display(value: unknown): string { return value === null || value === undefined || value === "" ? "—" : String(value); }
function measurementValue(measurements: Array<Record<string, unknown>> | undefined, types: string[]) { return measurements?.find((item) => types.includes(String(item.type ?? item.measurementType ?? "").toUpperCase())); }
function calculateBmi(weightKg: number | null, heightCm: number | null): number | null { if (!weightKg || !heightCm || weightKg <= 0 || heightCm <= 0) return null; return Number((weightKg / Math.pow(heightCm / 100, 2)).toFixed(1)); }
function getWeightStatus(bmi?: number | null): { text: "(Underweight)" | "(Normal weight)" | "(Obese)" | "(Extreme obese)"; textClass: string; badgeClass: string; activeClass: string; } {
  if (bmi == null || Number.isNaN(bmi)) return { text: "(Normal weight)", textClass: "text-slate-500", badgeClass: "bg-slate-100 text-slate-600", activeClass: "ring-slate-300" };
  if (bmi < 18.5) return { text: "(Underweight)", textClass: "text-amber-700", badgeClass: "bg-amber-100 text-amber-800", activeClass: "ring-amber-400" };
  if (bmi <= 24.9) return { text: "(Normal weight)", textClass: "text-emerald-700", badgeClass: "bg-emerald-100 text-emerald-800", activeClass: "ring-emerald-400" };
  if (bmi <= 29.9) return { text: "(Obese)", textClass: "text-orange-700", badgeClass: "bg-orange-100 text-orange-800", activeClass: "ring-orange-400" };
  return { text: "(Extreme obese)", textClass: "text-red-700", badgeClass: "bg-red-100 text-red-800", activeClass: "ring-red-400" };
}
function LargeAction({ href, icon, label }: { href: string; icon: ReactNode; label: string }) { return <Link href={href} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white px-4 py-3 text-xs font-bold text-[#0b2d54] shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-md focus:outline-none focus-visible:ring-2 focus-visible:ring-[#24c1c4]">{icon}{label}</Link>; }
function CountPill({ icon, count, label }: { icon: ReactNode; count: number; label: string }) { return <div className="flex min-h-12 items-center gap-2 rounded-2xl bg-white/90 px-4 py-2.5 text-[#0b2d54] shadow-sm ring-1 ring-slate-100">{icon}<span className="text-sm font-extrabold">{count}</span><span className="text-xs font-semibold">{label}</span></div>; }

function WeightBodySizeCard({ weightKg, heightCm, bmi, patientId, reload }: { weightKg: number | null | undefined; heightCm: number | null | undefined; bmi: number | null | undefined; patientId?: string; reload: () => Promise<void> }) {
  const [editingWeight, setEditingWeight] = useState<number | null>(null);
  const [manualWeight, setManualWeight] = useState("");
  const [inputOpen, setInputOpen] = useState(false);
  const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle");
  const canEdit = !patientId;
  const minWeight = 20;
  const maxWeight = 250;
  const currentWeight = editingWeight ?? (weightKg != null ? Number(weightKg) : 60);
  const liveBmi = calculateBmi(currentWeight, heightCm != null ? Number(heightCm) : null) ?? (bmi != null ? Number(bmi) : null);
  const weightStatus = getWeightStatus(liveBmi);
  const sliderPercent = ((currentWeight - minWeight) / (maxWeight - minWeight)) * 100;
  const thresholdPercent = (bmiValue: number) => { if (!heightCm) return null; const thresholdWeight = bmiValue * Math.pow(Number(heightCm) / 100, 2); return Math.max(0, Math.min(100, ((thresholdWeight - minWeight) / (maxWeight - minWeight)) * 100)); };
  const lowEnd = thresholdPercent(18.5);
  const normalEnd = thresholdPercent(24.9);
  const obeseEnd = thresholdPercent(29.9);
  const trackBackground = lowEnd != null && normalEnd != null && obeseEnd != null ? `linear-gradient(to right, #f59e0b 0%, #f59e0b ${lowEnd}%, #10b981 ${lowEnd}%, #10b981 ${normalEnd}%, #f97316 ${normalEnd}%, #f97316 ${obeseEnd}%, #ef4444 ${obeseEnd}%, #ef4444 100%)` : "linear-gradient(to right, #f59e0b 0%, #f59e0b 33%, #10b981 33%, #10b981 66%, #ef4444 66%, #ef4444 100%)";
  const persistWeight = async (weightOverride?: number) => {
    const nextWeight = weightOverride ?? editingWeight;
    if (!canEdit || nextWeight == null || saveState === "saving") return;
    if (!heightCm) { setSaveState("error"); return; }
    try { setSaveState("saving"); await healthHomeService.updateWeight(nextWeight, Number(heightCm)); setSaveState("saved"); setInputOpen(false); await reload(); }
    catch (error) { console.error("Failed to update weight:", error); setSaveState("error"); }
  };
  const handleWeightChange = (value: string) => { const nextWeight = Number(value); if (!Number.isFinite(nextWeight)) return; setEditingWeight(Number(nextWeight.toFixed(1))); setSaveState("idle"); };
  const handleManualWeightChange = (value: string) => {
    setManualWeight(value);
    const nextWeight = Number(value);
    if (!Number.isFinite(nextWeight) || nextWeight < minWeight || nextWeight > maxWeight) return;
    setEditingWeight(Number(nextWeight.toFixed(1)));
    setSaveState("idle");
  };
  const openInput = () => { if (!canEdit) return; setManualWeight(currentWeight.toString()); setInputOpen(true); setSaveState("idle"); };
  const statusMessage = saveState === "saving" ? "Saving your weight…" : saveState === "saved" ? "Weight saved" : saveState === "error" ? "Could not save. Try again." : canEdit ? "Move the slider or select BMI to enter your weight" : "Family health information is view-only";
  return <div className={`mt-5 rounded-[28px] bg-white p-5 shadow-sm ring-2 ${weightStatus.activeClass} sm:p-6`}>
    <div className="flex flex-col gap-5">
      <div className="flex items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#0b2d54]/8" aria-hidden="true"><Weight className="h-7 w-7 text-[#0b2d54]" /></div><div><h3 className="text-lg font-black text-[#0b2d54]">Weight &amp; Body Size</h3><p className="mt-1 text-xs font-bold text-slate-500">Your current body weight</p></div></div><span className={`shrink-0 rounded-full px-3 py-1.5 text-[11px] font-black uppercase tracking-wide ${weightStatus.badgeClass}`}>{weightStatus.text.replace(/[()]/g, "")}</span></div>
      <button type="button" onClick={openInput} disabled={!canEdit} className="w-full rounded-3xl bg-slate-50 px-4 py-4 text-left ring-1 ring-slate-100 transition hover:ring-[#24c1c4]/40 focus:outline-none focus-visible:ring-2 focus-visible:ring-[#24c1c4] disabled:cursor-default sm:px-5 sm:py-4">
        <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-3xl font-black leading-none tracking-tight text-[#0b2d54] sm:text-4xl">{currentWeight.toFixed(1)} <span className="text-xl font-extrabold text-slate-500">kg</span></p><p className="mt-1.5 text-[10px] font-extrabold uppercase tracking-wider text-slate-400">Weight</p></div><div className="text-right"><p className="text-[11px] font-black text-slate-400">BMI</p><p className={`text-2xl font-black ${weightStatus.textClass}`}>{liveBmi != null ? liveBmi.toFixed(1) : "—"}</p><p className={`text-[11px] font-extrabold ${weightStatus.textClass}`}>{weightStatus.text}</p></div></div>
        {canEdit && <p className="mt-2.5 text-[11px] font-bold text-[#0b2d54]">Tap BMI to enter your weight</p>}
      </button>
      <div className="relative pt-2"><div className="mb-3 flex items-center justify-between text-[11px] font-black uppercase tracking-wider text-slate-500"><span>LOW</span><span>JUST RIGHT</span><span>HIGH</span></div><div className="relative h-14 overflow-visible rounded-2xl"><div className="absolute inset-x-0 top-1/2 h-12 -translate-y-1/2 rounded-2xl shadow-inner" style={{ background: trackBackground }} aria-hidden="true" /><div className="pointer-events-none absolute top-1/2 z-10 h-[62px] w-[6px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#0b2d54] shadow-[0_4px_12px_rgba(11,45,84,0.35)] ring-4 ring-white transition-[left] duration-75" style={{ left: `${Math.max(0, Math.min(100, sliderPercent))}%` }} aria-hidden="true"><span className="absolute -top-3 left-1/2 h-3 w-3 -translate-x-1/2 rounded-full bg-[#0b2d54] ring-2 ring-white" /></div><input type="range" min={minWeight} max={maxWeight} step="0.1" value={currentWeight} disabled={!canEdit || !heightCm} onChange={(event) => handleWeightChange(event.target.value)} onPointerUp={() => void persistWeight()} onKeyUp={(event) => { if (event.key === "ArrowLeft" || event.key === "ArrowRight" || event.key === "Home" || event.key === "End") void persistWeight(); }} onBlur={() => void persistWeight()} aria-label="Weight in kilograms" className="absolute inset-0 z-20 h-full w-full cursor-grab opacity-0 disabled:cursor-not-allowed" /></div><div className="mt-3 flex justify-between text-[11px] font-bold text-slate-400"><span>{minWeight} kg</span><span>{maxWeight} kg</span></div></div>
      <div className="flex min-h-12 items-center justify-between gap-3 rounded-2xl bg-[#0b2d54]/5 px-4 py-3 text-xs font-bold"><span className={saveState === "error" ? "text-red-700" : saveState === "saved" ? "text-emerald-700" : "text-slate-600"}>{statusMessage}</span>{canEdit && <button type="button" onClick={() => void persistWeight()} disabled={editingWeight == null || saveState === "saving" || !heightCm} className="min-h-11 rounded-xl bg-[#0b2d54] px-4 py-2 text-xs font-black text-white shadow-sm transition hover:bg-[#071f3a] disabled:cursor-not-allowed disabled:opacity-40">{saveState === "saving" ? "Saving…" : "Save weight"}</button>}</div>
    </div>
    {inputOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0b2d54]/45 p-4" role="dialog" aria-modal="true" aria-labelledby="bmi-weight-dialog-title"><div className="w-full max-w-md rounded-[28px] bg-white p-6 shadow-2xl"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#24c1c4]/12"><Weight className="h-6 w-6 text-[#0b2d54]" /></div><div><h4 id="bmi-weight-dialog-title" className="text-lg font-black text-[#0b2d54]">Update your weight</h4><p className="text-xs font-medium text-slate-500">Enter your weight in kilograms.</p></div></div><label className="mt-6 block text-xs font-extrabold text-[#0b2d54]">Weight (kg)<input type="number" inputMode="decimal" min={minWeight} max={maxWeight} step="0.1" value={manualWeight} onChange={(event) => handleManualWeightChange(event.target.value)} autoFocus className="mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-4 text-2xl font-black text-[#0b2d54] outline-none focus:border-[#24c1c4] focus:ring-2 focus:ring-[#24c1c4]/20" placeholder="e.g. 60, 70 or 71" /></label><p className="mt-2 text-[11px] font-semibold text-slate-500">BMI: {liveBmi != null ? liveBmi.toFixed(1) : "—"} · {weightStatus.text}</p><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setInputOpen(false)} className="min-h-11 rounded-xl px-4 py-2 text-xs font-black text-slate-600 ring-1 ring-slate-200">Cancel</button><button type="button" onClick={() => void persistWeight(Number(manualWeight))} disabled={!manualWeight || Number(manualWeight) < minWeight || Number(manualWeight) > maxWeight || !heightCm || saveState === "saving"} className="min-h-11 rounded-xl bg-[#0b2d54] px-5 py-2 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{saveState === "saving" ? "Saving…" : "Save weight"}</button></div></div></div>}
  </div>;
}

export default function HealthHome() {
  const { data, loading, error, reload } = useDashboard();
  const searchParams = useSearchParams();
  const patientId = searchParams.get("patientId") || undefined;
  if (loading) return <ProtectedRoute><main className="min-h-screen bg-[#f5f8fb] p-4 sm:p-8"><div className="mx-auto max-w-5xl space-y-4" aria-busy="true"><div className="h-32 animate-pulse rounded-[28px] bg-white" />{Array.from({ length: 3 }).map((_, i) => <div key={i} className="h-64 animate-pulse rounded-[28px] bg-white" />)}</div></main></ProtectedRoute>;
  if (error || !data) return <ProtectedRoute><main className="min-h-screen bg-[#f5f8fb] p-4 sm:p-8"><div className="mx-auto max-w-xl rounded-[28px] border border-red-200 bg-white p-6"><TriangleAlert className="h-6 w-6 text-red-600" /><h1 className="mt-4 text-xl font-extrabold text-[#0b2d54]">Your health screen could not load</h1><p className="mt-2 text-sm text-slate-500">Your health information has not been changed. Please try again.</p><button type="button" onClick={reload} className="mt-5 min-h-11 rounded-xl bg-[#0b2d54] px-5 text-sm font-extrabold text-white">Try again</button></div></main></ProtectedRoute>;
  const firstName = data.patient?.firstName || data.profile?.preferredName || data.profile?.firstName || "there";
  const medications = data.today?.activeMedications ?? [];
  const appointments = data.today?.upcomingAppointments ?? [];
  const activeGoals = (data.goals ?? []).filter((goal) => String(goal.status).toUpperCase() !== "ACHIEVED").length;
  const conditions = data.healthSnapshot?.activeConditions ?? [];
  const allergies = data.healthSnapshot?.allergies ?? [];
  const immunizations = Array.isArray(data.immunizations) ? data.immunizations : (data.healthSnapshot?.immunizations ?? []);
  const measurements = data.healthSnapshot?.latestMeasurements ?? [];
  const watchMeasurements = data.wearables?.latestMeasurements ?? [];
  const devices = data.wearables?.devices ?? [];
  const bloodPressure = measurementValue(measurements, ["BLOOD_PRESSURE", "BP"]);
  const heart = measurementValue(watchMeasurements as Array<Record<string, unknown>>, ["HEART_RATE", "HEART"]) ?? measurementValue(measurements, ["HEART_RATE", "HEART"]);
  const bpValue = bloodPressure ? `${display(bloodPressure.value)} ${display(bloodPressure.unit)}` : "—";
  const heartValue = heart ? `${display(heart.value)} ${display(heart.unit)}` : "—";
  const watchConnected = devices.length > 0;
  return <ProtectedRoute><main className="min-h-screen bg-[#f5f8fb] text-slate-800"><header className="border-b border-[#24c1c4]/10 bg-white"><div className="mx-auto flex min-h-[68px] max-w-5xl items-center justify-between px-4 sm:px-6"><img src="/logo-navbar.png" alt="Sympto" className="h-10 w-auto" /><span className="rounded-full bg-[#24c1c4]/10 px-3 py-1.5 text-xs font-extrabold text-[#0b2d54]">My Health</span></div></header>
    <div className="mx-auto max-w-5xl space-y-4 px-4 py-5 sm:px-6 sm:py-7">
      <section className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-[#0b2d54] to-[#24c1c4] p-6 text-white shadow-[0_16px_40px_rgba(11,45,84,0.14)] sm:p-7"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-white/75">My Health</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">Hello, {firstName} 👋</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/85">Your important health information is organised for you. Just choose what you need.</p></section>
      <section className="overflow-hidden rounded-[28px] border border-[#24c1c4]/25 bg-white shadow-sm"><div className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#24c1c4]/12">🟢</div><h2 className="mt-4 text-2xl font-black text-[#0b2d54] sm:text-3xl">What do I do today?</h2><p className="mt-1 text-sm font-medium text-slate-600">Your medicines, clinic visits and care plan are here.</p></div><Link href="/today" className="flex h-11 w-11 items-center justify-center rounded-full bg-[#24c1c4]/10 text-[#0b2d54]"><ArrowRight className="h-5 w-5" /></Link></div><div className="mt-5 grid gap-2.5 sm:grid-cols-3"><LargeAction href="/medications" icon={<Pill className="h-5 w-5" />} label={`${medications.length} medicine${medications.length === 1 ? "" : "s"}`} /><LargeAction href="/appointments" icon={<CalendarDays className="h-5 w-5" />} label={`${appointments.length} clinic visit${appointments.length === 1 ? "" : "s"}`} /><LargeAction href="/health-goals" icon={<CheckCircle2 className="h-5 w-5" />} label={`${activeGoals} care goal${activeGoals === 1 ? "" : "s"}`} /></div><div className="mt-5 border-t border-[#24c1c4]/15 pt-4"><div className="flex items-center justify-between rounded-2xl bg-[#0b2d54] p-4 text-white"><div className="flex items-center gap-3"><Watch className="h-6 w-6" /><div><p className="text-base font-black">⌚ Link Watch</p><p className="text-xs text-white/70">{watchConnected ? "Your watch is connected" : "Bluetooth health watch"}</p></div></div><span className="rounded-xl bg-white/10 px-3 py-2 text-sm font-extrabold">{watchConnected ? "Connected" : "Not linked"}</span></div></div></div></section>
      <section className="overflow-hidden rounded-[28px] border border-[#24c1c4]/25 bg-white shadow-sm"><div className="p-5 sm:p-6"><Link href="/health-passport" className="block"><div className="flex items-start justify-between gap-4"><div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#24c1c4]/12">🔴</div><h2 className="mt-4 text-2xl font-black text-[#0b2d54] sm:text-3xl">My Clinic Card</h2><p className="mt-1 text-sm font-medium text-slate-600">Show this information when you visit a nurse or doctor.</p></div><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#24c1c4]/10"><ArrowRight className="h-5 w-5" /></span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-[#f5f8fb] p-4"><div className="flex items-center gap-2 text-xs font-bold text-slate-500"><HeartPulse className="h-5 w-5 text-[#24c1c4]" />BLOOD PRESSURE</div><p className="mt-2 text-3xl font-black text-[#0b2d54]">{bpValue}</p></div><div className="rounded-2xl bg-[#f5f8fb] p-4"><div className="flex items-center gap-2 text-xs font-bold text-slate-500"><Watch className="h-5 w-5 text-[#24c1c4]" />❤️ WATCH HEART</div><p className="mt-2 text-3xl font-black text-[#0b2d54]">{heartValue}</p></div></div><div className="mt-3 grid gap-2.5 sm:grid-cols-3"><CountPill icon={<ShieldCheck className="h-5 w-5 text-[#24c1c4]" />} count={conditions.length} label="conditions" /><CountPill icon={<TriangleAlert className="h-5 w-5 text-[#24c1c4]" />} count={allergies.length} label="allergies" /><CountPill icon={<CheckCircle2 className="h-5 w-5 text-[#24c1c4]" />} count={immunizations.length} label="vaccines" /></div></Link><WeightBodySizeCard weightKg={data.healthSnapshot?.weightKg} heightCm={data.healthSnapshot?.heightCm} bmi={data.healthSnapshot?.bmi} patientId={patientId} reload={reload} /></div></section>
      <section className="overflow-hidden rounded-[28px] border border-[#24c1c4]/25 bg-white shadow-sm"><Link href="/health-journal" className="block p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#24c1c4]/12">🔵</div><h2 className="mt-4 text-2xl font-black text-[#0b2d54] sm:text-3xl">My History &amp; Papers</h2><p className="mt-1 text-sm font-medium text-slate-600">One simple folder for your health story and important papers.</p></div><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#24c1c4]/10"><ArrowRight className="h-5 w-5" /></span></div><div className="mt-5 rounded-2xl bg-[#f5f8fb] p-4"><div className="flex items-center gap-4"><FolderOpen className="h-7 w-7 text-[#24c1c4]" /><div><p className="text-base font-black text-[#0b2d54]">📁 Open my health folder</p><p className="mt-1 text-xs text-slate-500">Episodes · Encounters · Lab results · Imaging · Documents</p></div></div></div></Link></section>
    </div></main></ProtectedRoute>;
}