"use client";

import Link from "next/link";
import { Activity, ArrowLeft, HeartPulse, ShieldCheck, Watch } from "lucide-react";
import ProtectedRoute from "@/components/auth/protected-route";
import { useDashboard } from "@/hooks/use-dashboard";

function label(value: unknown) { return String(value ?? "Measurement").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()); }
function date(value: unknown) { if (!value) return "Not recorded"; const d = new Date(String(value)); return Number.isNaN(d.getTime()) ? String(value) : new Intl.DateTimeFormat("en-ZA", { dateStyle: "medium", timeStyle: "short" }).format(d); }

export default function VitalsPage() {
  const { data, loading, error, reload } = useDashboard();
  const measurements = data?.healthSnapshot?.latestMeasurements ?? [];
  const devices = data?.healthSnapshot?.connectedDevices ?? [];
  return <ProtectedRoute><main className="min-h-screen bg-[#f5f8fb]"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/my-health" className="inline-flex items-center gap-2 text-sm font-semibold text-[#0b2d54]"><ArrowLeft className="h-4 w-4" />My Health</Link><section className="mt-6 rounded-[28px] bg-gradient-to-br from-[#0b2d54] to-[#24c1c4] p-8 text-white"><Activity className="h-6 w-6" /><h1 className="mt-4 text-3xl font-bold">Vitals & measurements</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/75">Your latest health measurements from authorised sources, presented as part of your personal health record.</p></section>{loading && <div className="mt-6 rounded-2xl bg-white p-6 text-sm text-slate-500">Loading your measurements…</div>}{error && <div className="mt-6 rounded-2xl bg-white p-6"><p className="font-semibold text-[#0b2d54]">We couldn't load your measurements.</p><button onClick={reload} className="mt-4 rounded-xl bg-[#0b2d54] px-4 py-2 text-sm font-semibold text-white">Try again</button></div>}{!loading && !error && <><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{measurements.map((item: any) => <div key={`${item.type}-${item.measuredAt}`} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2 text-[#24c1c4]"><HeartPulse className="h-4 w-4" /><span className="text-xs font-bold uppercase tracking-wide">{label(item.type)}</span></div><p className="mt-3 text-2xl font-bold text-[#0b2d54]">{item.value} <span className="text-sm font-medium text-slate-400">{item.unit}</span></p><p className="mt-1 text-xs text-slate-400">{date(item.measuredAt)}</p></div>)}</section><section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-3"><Watch className="h-5 w-5 text-[#24c1c4]" /><div><h2 className="font-bold text-[#0b2d54]">Connected sources</h2><p className="text-xs text-slate-400">Devices contributing to your health record</p></div></div>{devices.length === 0 ? <p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">No connected devices yet.</p> : <div className="mt-5 grid gap-3 sm:grid-cols-2">{devices.map((device: any) => <div key={device.id} className="rounded-2xl bg-slate-50 p-4"><p className="font-semibold text-[#0b2d54]">{device.manufacturer || "Device"} {device.model || ""}</p><p className="mt-1 text-xs text-slate-500">{device.status || "Connected"} · {device.measurementCount ?? 0} measurements</p></div>)}</div>}</section><div className="mt-6 rounded-2xl border border-[#24c1c4]/20 bg-[#24c1c4]/5 p-5"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-[#0b2d54]" /><p className="text-sm leading-6 text-slate-600">Wearable and device data remains part of your personal health journey. Sympto uses it to help you understand trends; it does not replace professional medical assessment.</p></div></div></>}</div></main></ProtectedRoute>;
}
