export type SmartFileClinicalResponse = {
  patient: {
    id: string;
    patientNumber: string | null;
    firstName: string;
    middleName: string | null;
    lastName: string;
    preferredName: string | null;
    dateOfBirth: Date | null;
    gender: string | null;
  };
  clinicalAccess: {
    canView: boolean;
    canUpdate: boolean;
    accessType: 'APPOINTMENT' | 'WALK_IN';
    appointmentId: string | null;
    consentExpiresAt: Date | null;
  };
  healthPassport: unknown;
  medicalRecord: unknown;
  conditions: unknown[];
  allergies: unknown[];
  immunisations: unknown[];
  medications: unknown[];
  prescriptions: unknown[];
  appointments: unknown[];
  encounters: unknown[];
  episodes: unknown[];
  vitals: unknown[];
  patientVitals: unknown[];
  symptoms: unknown[];
  diagnoses: unknown[];
  procedures: unknown[];
  labResults: unknown[];
  imaging: unknown[];
  carePlans: unknown[];
  referrals: unknown[];
  clinicalDocuments: unknown[];
  healthJournalEntries: unknown[];
  patientMeasurements: unknown[];
  wearableWellnessMetrics: unknown[];
  wearableDevices: unknown[];
  generatedAt: Date;
};
